### ISSUE TITLE
Adding the possibility to load a configuration at Ecologits.init()

### ISSUE THREAD

**Issue by NP4567-dev** [genai-impact/ecologits#98]
### Description

**Context:**
In this first issue on the topic, the aim is to enable the user to provide a configuration for both existing parameters (providers and electricity_mix_zone).
The addition of other configuration parameters, while taken into account will be addressed in other issues
It is important to stay compatible with older versions while guaranteeing enough flexibility to implement future configuration features.

**Changes:**
Add the configuration argument. It is a path pointing to a locally stored yaml configuration in [Ecologits.init()](https://github.com/genai-impact/ecologits/blob/d4baace475525ebd452eaaeda1b337335373c016/ecologits/_ecologits.py#L124).
The file could have the following formatting for now:

``` yaml ecologits.config.yaml
providers:
    - mistral
    - openai
electricity_mix_zone: WOR

```
I see three possible ways to handle it:

- Ecologits.init() now expects a _Config: this is pretty simple but not retrocompatible and would probably remove some typing helps for users
- Ecologits.init() can now handle either the current parameters or a _Config parameter. This means the priority between arguments must be set (if both a config and current parameters are provided, which value is kept?). Also, for each additionnal parameter handled by the configuration, it will start a discussion on wether it should be added to the base parameters of the init function
- Add a different 'init_with_config' function, expecting a _Config object to the Ecologits class. This goes towards having different uses in experimental and production settings for users, but also might be a bit harder to maintain.

_This questions have to be answered before proceeding:_
- Should an unvalid configuration (non existing provider or electricity mix) raise an exception from the get go?
- Should a missing parameter (neither key nor value in yaml) in configuration be replaced by a default value? (in the future wether to fallback on default values could be a parameter)
- Should an empty parameter (key but empty value in yaml) in configuration be considered an error from the user and raise an exception?
- What should be the specific value for when the user wants all the providers to be loaded? It could be just a null value or a specific word.

**Other remarks: **
Not in this feature but could be added later:
- Having a specific electricity_mix for a given provider
- Providing custom model infos
- Error handling configuration (should a missing info raise an error or just be loggued)
- ...

Feel free to correct or add anything 😃

**Comment by samuelrince** [comment]
Thanks for drafting this issue, I'll add some bits on what I imagined as well!

* We don't necessarily need to keep the `_Config` dataclass, we can design a new system to handle configuration properly.
* I think it is okay and practical to have multiple ways of configuring the lib (init() method, config file, ...) as long as we define an order to apply the config. (parameters from init() > config file > default values).
* I'd rather use a toml file has the python ecosystem is converging to that file format instead of yaml. Plus, toml is part of the standard library since 3.10 or 3.11 and not yaml.
* About custom models or aliases, I don't think it should be integrated within this config file. It can take a lot of space, and it could be shared between projects of a team, for instance. We should consider it as loading an external/additional "model_repository" from a local file or from a cached file (in`~/.ecologits` or `~/.cache/ecologits` directories) or from a URL.

Example of what it could look like:

```toml
[ecologits]
region="WOR"		# Can be removed, as it is the default value can be named `zone` as well, or something else...
providers=[
  "openai",
  "anthropic",		# Active, but no custom config
  "mistralai",
  "scaleway"		# Not supported right now, just to give an example with a cloud provide
]

[ecologits.openai]
region="USA"		# Location set to the US, we will select according values for eletricity mix, off-site water consumption...

[ecologits.mistralai]
region="FRA"		# Location set to France, we will select according values for eletricity mix, off-site water consumption...

[ecologits.scaleway]
region="fr-par"		# This parameter could also accept cloud regions
pue=1.18			# Known PUE and WUE of the specific data center
wue=0.4
wue_offsite=3.2		# Off-site WUE also changed for FRA
```

We can add more specific parameters to precisely customize the methodology regarding electricity mix, embodied impacts of hardware and more. But, let's do it step-by-step with simple and useful things first!
